---
- hosts: back
  remote_user: vagrant
  tasks:

  - name: udtate apt-get package cache to latests version
    sudo: yes
    apt: update_cache=yes

  - name: install python dependencies
    sudo: yes
    apt: name={{ item }} state=present
    with_items:
      - build-essential 
      - libreadline-gplv2-dev
      - libncursesw5-dev
      - libssl-dev
      - libsqlite3-dev
      - tk-dev
      - libgdbm-dev
      - libc6-dev
      - libbz2-dev
      - make
      - curl
      - python-pip

  - name: download python 2.7.5
    sudo: yes
    get_url: url=http://python.org/ftp/python/2.7.5/Python-2.7.5.tgz dest=/tmp/Python-2.7.5.tgz

  - name: untar python 2.7.5
    sudo: yes
    unarchive: copy=no src=/tmp/Python-2.7.5.tgz dest=/tmp/

  - name: make and install python 2.7.5
    sudo: yes
    shell: "{{ item }}"
    with_items:
      - ./configure
      - make
      - make altinstall
    args:
      chdir: /tmp/Python-2.7.5/
